[build]
  command = "remix vite:build"
  publish = "public"  # or your actual Remix build output folder, often "public" or "dist/client"

[build.environment]
  NODE_ENV = "development"   # Ensures devDependencies are installed during build
